# Generated by Django 5.0.6 on 2025-09-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GridData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("voltage", models.FloatField()),
                ("current", models.FloatField()),
                ("anomaly", models.BooleanField(default=False)),
            ],
        ),
    ]
