# Generated by Django 5.0.6 on 2025-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="griddata",
            name="attack_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
