# Generated by Django 5.0.6 on 2025-09-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
